.PHONY: clean All

All:
	@echo "----------Building project:[ 6ChallengeSection - Debug ]----------"
	@cd "6ChallengeSection" && "$(MAKE)" -f  "6ChallengeSection.mk"
clean:
	@echo "----------Cleaning project:[ 6ChallengeSection - Debug ]----------"
	@cd "6ChallengeSection" && "$(MAKE)" -f  "6ChallengeSection.mk" clean
