.PHONY: clean All

All:
	@echo "----------Building project:[ 915StringStream - Debug ]----------"
	@cd "915StringStream" && "$(MAKE)" -f  "915StringStream.mk"
clean:
	@echo "----------Cleaning project:[ 915StringStream - Debug ]----------"
	@cd "915StringStream" && "$(MAKE)" -f  "915StringStream.mk" clean
