.PHONY: clean All

All:
	@echo "----------Building project:[ 5Re-Do_ChallengeSection - Debug ]----------"
	@cd "5Re-Do_ChallengeSection" && "$(MAKE)" -f  "5Re-Do_ChallengeSection.mk"
clean:
	@echo "----------Cleaning project:[ 5Re-Do_ChallengeSection - Debug ]----------"
	@cd "5Re-Do_ChallengeSection" && "$(MAKE)" -f  "5Re-Do_ChallengeSection.mk" clean
