.PHONY: clean All

All:
	@echo "----------Building project:[ 9ChallengeSection - Debug ]----------"
	@cd "9ChallengeSection" && "$(MAKE)" -f  "9ChallengeSection.mk"
clean:
	@echo "----------Cleaning project:[ 9ChallengeSection - Debug ]----------"
	@cd "9ChallengeSection" && "$(MAKE)" -f  "9ChallengeSection.mk" clean
