.PHONY: clean All

All:
	@echo "----------Building project:[ 3.Vectors - Debug ]----------"
	@cd "Vectors" && "$(MAKE)" -f  "3.Vectors.mk"
clean:
	@echo "----------Cleaning project:[ 3.Vectors - Debug ]----------"
	@cd "Vectors" && "$(MAKE)" -f  "3.Vectors.mk" clean
