.PHONY: clean All

All:
	@echo "----------Building project:[ 6ChallengeTwo - Debug ]----------"
	@cd "6ChallengeTwo" && "$(MAKE)" -f  "6ChallengeTwo.mk"
clean:
	@echo "----------Cleaning project:[ 6ChallengeTwo - Debug ]----------"
	@cd "6ChallengeTwo" && "$(MAKE)" -f  "6ChallengeTwo.mk" clean
