.PHONY: clean All

All:
	@echo "----------Building project:[ UpdatedTemplate - Debug ]----------"
	@cd "UpdatedTemplate" && "$(MAKE)" -f  "UpdatedTemplate.mk"
clean:
	@echo "----------Cleaning project:[ UpdatedTemplate - Debug ]----------"
	@cd "UpdatedTemplate" && "$(MAKE)" -f  "UpdatedTemplate.mk" clean
