.PHONY: clean All

All:
	@echo "----------Building project:[ 5ChallengeSection - Debug ]----------"
	@cd "5ChallengeSection" && "$(MAKE)" -f  "5ChallengeSection.mk"
clean:
	@echo "----------Cleaning project:[ 5ChallengeSection - Debug ]----------"
	@cd "5ChallengeSection" && "$(MAKE)" -f  "5ChallengeSection.mk" clean
