.PHONY: clean All

All:
	@echo "----------Building project:[ 3ArraysByPointers - Debug ]----------"
	@cd "3ArraysByPointers" && "$(MAKE)" -f  "3ArraysByPointers.mk"
clean:
	@echo "----------Cleaning project:[ 3ArraysByPointers - Debug ]----------"
	@cd "3ArraysByPointers" && "$(MAKE)" -f  "3ArraysByPointers.mk" clean
