.PHONY: clean All

All:
	@echo "----------Building project:[ BasicOutputWriting - Debug ]----------"
	@cd "BasicOutputWriting" && "$(MAKE)" -f  "BasicOutputWriting.mk"
clean:
	@echo "----------Cleaning project:[ BasicOutputWriting - Debug ]----------"
	@cd "BasicOutputWriting" && "$(MAKE)" -f  "BasicOutputWriting.mk" clean
