.PHONY: clean All

All:
	@echo "----------Building project:[ 10ChallengeSection - Debug ]----------"
	@cd "10ChallengeSection" && "$(MAKE)" -f  "10ChallengeSection.mk"
clean:
	@echo "----------Cleaning project:[ 10ChallengeSection - Debug ]----------"
	@cd "10ChallengeSection" && "$(MAKE)" -f  "10ChallengeSection.mk" clean
