.PHONY: clean All

All:
	@echo "----------Building project:[ VariablesBasics - Debug ]----------"
	@cd "VariablesAndNames" && "$(MAKE)" -f  "VariablesBasics.mk"
clean:
	@echo "----------Cleaning project:[ VariablesBasics - Debug ]----------"
	@cd "VariablesAndNames" && "$(MAKE)" -f  "VariablesBasics.mk" clean
