.PHONY: clean All

All:
	@echo "----------Building project:[ 7ChallengeSection - Debug ]----------"
	@cd "ChallengeDifSource\Challenge" && "$(MAKE)" -f  "7ChallengeSection.mk"
clean:
	@echo "----------Cleaning project:[ 7ChallengeSection - Debug ]----------"
	@cd "ChallengeDifSource\Challenge" && "$(MAKE)" -f  "7ChallengeSection.mk" clean
