.PHONY: clean All

All:
	@echo "----------Building project:[ 915DeepCopy - Debug ]----------"
	@cd "95DeepCopy" && "$(MAKE)" -f  "915DeepCopy.mk"
clean:
	@echo "----------Cleaning project:[ 915DeepCopy - Debug ]----------"
	@cd "95DeepCopy" && "$(MAKE)" -f  "915DeepCopy.mk" clean
